table Medidas
	lineageTag: 9ed1958b-40a2-4250-bc9f-e809ae31a944

	measure '$ total Lançamentos' =
			
			SUMX(
			    fLancamentos,
			    fLancamentos[valor] * RELATED(dPlanoConta[tipoLancamento])
			)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 0421cd52-03d2-4f61-8ccd-b455526ec22b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Coluna 1'
		dataType: string
		lineageTag: 32890ab4-5970-4c00-a14e-7ea50940e49e
		summarizeBy: none
		sourceColumn: Coluna 1

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

