table Medidas
	lineageTag: 9ed1958b-40a2-4250-bc9f-e809ae31a944

	measure '$ total Lançamentos' =
			
			SUMX(
			    fLancamentos,
			    fLancamentos[valor] * RELATED(dPlanoConta[tipoLancamento])
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 0421cd52-03d2-4f61-8ccd-b455526ec22b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '$ Realizado' =
			
			VAR vSubtotal = SELECTEDVALUE(dEstruturaDRE[subtotal])
			VAR vIndex = SELECTEDVALUE(dEstruturaDRE[index])
			VAR vDetalharN2 = SELECTEDVALUE(dPlanoConta[detalharN2])
			VAR vTotal = [$ total Lançamentos]
			VAR vAcumulado =
			CALCULATE(
			    [$ total Lançamentos],
			    ALLSELECTED(dEstruturaDRE),
			    VALUES(dEstruturaDRE[empresa]), //Devolva o contexto de empresa
			    dEstruturaDRE[index] < vIndex
			)
			RETURN
			SWITCH(
			    TRUE(),
			    vSubtotal = 1 && ISINSCOPE(dPlanoConta[descricaoN1]), BLANK(),
			    vDetalharN2 = 0 && ISINSCOPE(dPlanoConta[descricaoN2]), BLANK(),
			    vSubtotal = 0, vTotal,
			    vSubtotal = 1, vAcumulado,
			    BLANK()
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: fbeb9bbc-008e-4b91-b1ee-fab8f4537e6d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '$ total Orçado' =
			
			SUMX(
			    fOrcamento,
			    fOrcamento[valor] * RELATED(dPlanoConta[tipoLancamento])
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: decff684-2827-4c42-a8f9-b3915367ae67

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '$ total Previsto' =
			
			SUMX(
			    fPrevisao,
			    fPrevisao[valor] * RELATED(dPlanoConta[tipoLancamento])
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: fa2ca25d-27b4-45b5-979e-e04194d1ea67

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '$ Orçado' =
			
			VAR vSubtotal = SELECTEDVALUE(dEstruturaDRE[subtotal])
			VAR vIndex = SELECTEDVALUE(dEstruturaDRE[index])
			VAR vDetalharN2 = SELECTEDVALUE(dPlanoConta[detalharN2])
			VAR vTotal = [$ total Orçado]
			VAR vAcumulado =
			CALCULATE(
			    [$ total Orçado],
			    ALLSELECTED(dEstruturaDRE),
			    VALUES(dEstruturaDRE[empresa]), //Devolva o contexto de empresa
			    dEstruturaDRE[index] < vIndex
			)
			RETURN
			SWITCH(
			    TRUE(),
			    vSubtotal = 1 && ISINSCOPE(dPlanoConta[descricaoN1]), BLANK(),
			    vDetalharN2 = 0 && ISINSCOPE(dPlanoConta[descricaoN2]), BLANK(),
			    vSubtotal = 0, vTotal,
			    vSubtotal = 1, vAcumulado,
			    BLANK()
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: baec2451-91b9-4d3a-bc58-70eb9d8e51bb

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '$ Previsto' =
			
			VAR vSubtotal = SELECTEDVALUE(dEstruturaDRE[subtotal])
			VAR vIndex = SELECTEDVALUE(dEstruturaDRE[index])
			VAR vDetalharN2 = SELECTEDVALUE(dPlanoConta[detalharN2])
			VAR vTotal = [$ total Previsto]
			VAR vAcumulado =
			CALCULATE(
			    [$ total Previsto],
			    ALLSELECTED(dEstruturaDRE),
			    VALUES(dEstruturaDRE[empresa]), //Devolva o contexto de empresa
			    dEstruturaDRE[index] < vIndex
			)
			RETURN
			SWITCH(
			    TRUE(),
			    vSubtotal = 1 && ISINSCOPE(dPlanoConta[descricaoN1]), BLANK(),
			    vDetalharN2 = 0 && ISINSCOPE(dPlanoConta[descricaoN2]), BLANK(),
			    vSubtotal = 0, vTotal,
			    vSubtotal = 1, vAcumulado,
			    BLANK()
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: cee615df-2a41-4b6f-ba9a-170e16fd6eff

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '$ Meta' =
			
			IF(
			    SELECTEDVALUE(auxMeta[auxMeta Pedido]) = 0,
			    [$ Orçado],
			    [$ Previsto]
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: c63d9d35-9e80-436b-b6dd-19cb28c9794d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '% Meta vs Realizado' =
			
			VAR vMeta = [$ Meta]
			VAR vRealizado = [$ Realizado]
			VAR vDif = vRealizado - vMeta
			RETURN
			DIVIDE(
			    vDif,
			    ABS(vMeta)
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: d9c65fca-f52b-4286-b504-512b35185dd3

	column 'Coluna 1'
		dataType: string
		isHidden
		lineageTag: 32890ab4-5970-4c00-a14e-7ea50940e49e
		summarizeBy: none
		sourceColumn: Coluna 1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

