table Medidas
	lineageTag: 9ed1958b-40a2-4250-bc9f-e809ae31a944

	measure '$ total Lançamentos' =
			
			SUMX(
			    fLancamentos,
			    fLancamentos[valor] * RELATED(dPlanoConta[tipoLancamento])
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 0421cd52-03d2-4f61-8ccd-b455526ec22b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '$ Realizado' =
			
			VAR vSubtotal = SELECTEDVALUE(dEstruturaDRE[subtotal])
			VAR vIndex = SELECTEDVALUE(dEstruturaDRE[index])
			VAR vDetalharN2 = SELECTEDVALUE(dPlanoConta[detalharN2])
			VAR vTotal = [$ total Lançamentos]
			VAR vAcumulado =
			CALCULATE(
			    [$ total Lançamentos],
			    ALLSELECTED(dEstruturaDRE),
			    VALUES(dEstruturaDRE[empresa]), //Devolva o contexto de empresa
			    dEstruturaDRE[index] < vIndex
			)
			RETURN
			SWITCH(
			    TRUE(),
			    vSubtotal = 1 && ISINSCOPE(dPlanoConta[descricaoN1]), BLANK(),
			    vDetalharN2 = 0 && ISINSCOPE(dPlanoConta[descricaoN2]), BLANK(),
			    vSubtotal = 0, vTotal,
			    vSubtotal = 1, vAcumulado,
			    BLANK()
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: fbeb9bbc-008e-4b91-b1ee-fab8f4537e6d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Coluna 1'
		dataType: string
		isHidden
		lineageTag: 32890ab4-5970-4c00-a14e-7ea50940e49e
		summarizeBy: none
		sourceColumn: Coluna 1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

